spring:
  datasource:
    name: spring-security-demo
    generate-unique-name: false

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

#logging:
#  level:
#    '[org.springframework.web]': "debug"
#    '[org.springframework.security]': "debug"
#    '[com.suhacan.springsecuritydemo]': "debug"